project_id = "nyzvjuzrkhdbuqlcxhzn"

[functions.generate-invoice]
verify_jwt = false

[functions.search]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.order-sms-notify]
verify_jwt = false

[functions.admin-invoice]
verify_jwt = false
