<?php
require_once __DIR__ . '/_helpers.php';

global $MEDIA_ALLOWED, $MEDIA_FOLDERS;

media_cors();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
  media_json(405, ['error' => 'Method not allowed']);
}

// Header-based auth
$folder    = $_SERVER['HTTP_X_MEDIA_FOLDER']    ?? '';
$filename  = $_SERVER['HTTP_X_MEDIA_FILENAME']  ?? '';
$timestamp = $_SERVER['HTTP_X_MEDIA_TIMESTAMP'] ?? '';
$token     = $_SERVER['HTTP_X_MEDIA_TOKEN']     ?? '';

if (!in_array($folder, $MEDIA_FOLDERS, true)) {
  media_json(400, ['error' => 'Invalid folder']);
}

// filename should be UUID.ext generated by edge function
if (!preg_match('/^[a-f0-9\-]{36}\.[a-z0-9]{2,5}$/i', $filename)) {
  media_json(400, ['error' => 'Invalid filename']);
}

if (!media_verify_token($folder, $filename, $timestamp, $token)) {
  media_json(401, ['error' => 'Invalid or expired token']);
}

if (empty($_FILES['file'])) {
  media_json(400, ['error' => 'No file uploaded']);
}

$file = $_FILES['file'];
if ($file['error'] !== UPLOAD_ERR_OK) {
  media_json(400, ['error' => 'Upload error: ' . $file['error']]);
}

$ext = strtolower(pathinfo($filename, PATHINFO_EXTENSION));
if (!isset($MEDIA_ALLOWED[$ext])) {
  media_json(400, ['error' => 'Extension not allowed']);
}

$expectedMime = $MEDIA_ALLOWED[$ext];
$isImage = strpos($expectedMime, 'image/') === 0;

// Size check
$maxSize = $isImage ? MEDIA_MAX_IMAGE_SIZE : MEDIA_MAX_PDF_SIZE;
if ($file['size'] > $maxSize) {
  media_json(413, ['error' => 'File too large']);
}

// MIME sniff
$finfo = finfo_open(FILEINFO_MIME_TYPE);
$actualMime = finfo_file($finfo, $file['tmp_name']);
finfo_close($finfo);

$mimeOk = ($actualMime === $expectedMime)
  || ($ext === 'jpg' && $actualMime === 'image/jpeg')
  || ($ext === 'jpeg' && $actualMime === 'image/jpeg');

if (!$mimeOk) {
  media_json(400, ['error' => 'File type mismatch: ' . $actualMime]);
}

// Build destination path: {folder}/{YYYY}/{MM}/{uuid}.{ext}
$year = date('Y');
$month = date('m');
$relDir = "$folder/$year/$month";
$absDir = rtrim(MEDIA_STORAGE_PATH, '/') . '/' . $relDir;

if (!is_dir($absDir)) {
  if (!mkdir($absDir, 0755, true) && !is_dir($absDir)) {
    media_json(500, ['error' => 'Failed to create directory']);
  }
}

$absPath = "$absDir/$filename";
$relPath = "$relDir/$filename";

if (!move_uploaded_file($file['tmp_name'], $absPath)) {
  media_json(500, ['error' => 'Failed to save file']);
}
@chmod($absPath, 0644);

$publicUrl = rtrim(MEDIA_BASE_URL, '/') . '/' . $relPath;
$width = null; $height = null; $thumbnailUrl = null;

if ($isImage && function_exists('getimagesize')) {
  $info = @getimagesize($absPath);
  if ($info) { $width = $info[0]; $height = $info[1]; }

  // Generate 400px thumbnail for jpg/png/webp
  if (in_array($ext, ['jpg','jpeg','png','webp'], true) && function_exists('imagecreatefromstring')) {
    try {
      $data = file_get_contents($absPath);
      $src = @imagecreatefromstring($data);
      if ($src && $width > 400) {
        $ratio = 400 / $width;
        $newW = 400;
        $newH = (int)round($height * $ratio);
        $thumb = imagecreatetruecolor($newW, $newH);
        // preserve transparency
        imagealphablending($thumb, false);
        imagesavealpha($thumb, true);
        imagecopyresampled($thumb, $src, 0,0,0,0, $newW,$newH, $width,$height);
        $thumbFilename = 'thumb_' . $filename;
        $thumbAbsPath = "$absDir/$thumbFilename";
        switch ($ext) {
          case 'png':  imagepng($thumb, $thumbAbsPath, 6); break;
          case 'webp': imagewebp($thumb, $thumbAbsPath, 80); break;
          default:     imagejpeg($thumb, $thumbAbsPath, 82);
        }
        imagedestroy($thumb);
        @chmod($thumbAbsPath, 0644);
        $thumbnailUrl = rtrim(MEDIA_BASE_URL, '/') . "/$relDir/$thumbFilename";
      }
      if ($src) imagedestroy($src);
    } catch (Throwable $e) { /* ignore thumbnail errors */ }
  }
}

media_json(200, [
  'url' => $publicUrl,
  'thumbnail_url' => $thumbnailUrl,
  'filename' => $filename,
  'folder' => $folder,
  'mime_type' => $expectedMime,
  'size_bytes' => (int)$file['size'],
  'width' => $width,
  'height' => $height,
  'storage_provider' => 'cpanel',
]);
